Moved linting to Makefile
iver-wharf/wharf-core pull request #41
Opened 2022-02-07 13:16 UTC by jilleJr

## Summary

- Added targets to `Makefile` for linting and other utilities like cleaning
- Removed linting from NPM scripts in `package.json`
- Simplified linting docs

## Motivation

Moves focus from relying on NPM for all linting stuff over to Makefile.

Based on https://github.com/iver-wharf/wharf-cmd/pull/31

2022-02-09 14:00 UTC, fredx30 approved these changes

2022-02-10 10:13 UTC, Alexamakans requested changes
`lint-fix` does not run `lint-fix-go`

2022-02-10 10:13 UTC, Alexamakans commented on Makefile
> +lint-fix: lint-fix-md
missing `lint-fix-go`
```suggestion
lint-fix: lint-fix-md lint-fix-go
```

2022-02-10 10:19 UTC, Alexamakans approved these changes

2022-02-22 05:42 UTC, merged